### ISSUE TITLE
Crash with Cotton Resources?

### ISSUE THREAD

**Issue by UnicorNora** [EnnuiL/CrookedCrooks#2]
https://hastebin.com/niyunilaje.yaml

**Comment by joaoh1** [comment]
Something tells me that the issue isn't with neither Cotton Resources and Crooked Crooks, since I don't mess with tooltips, however, I managed to find a huge issue where Static Data was required by this mod's MCDict fork despite making it optional, could you see if [this version](https://github.com/joaoh1/CrookedCrooks/suites/1606867361/artifacts/29368171) fixes the crash?
