### ISSUE TITLE
curse of thorns book crashes

### ISSUE THREAD

**Issue by KlaraChaos** [EnnuiL/CrookedCrooks#4]
curse of thorns book crases the game if ys shift hover hover it to show enchament discription 

crash log https://pastebin.com/K9u7Jbte

**Comment by EnnuiL** [comment]
Wait, there's two of them? While I only accounted for Enchantment Descriptions, Enchanted Tooltips shouldn't have crashed at all;
I did find out why: that mod is trying to get the name of the enchantment type of my enchantment, however, since the type is null, it crashes; Due to a lack of an enchantment API, the null that I'm using was the only solution for making it apply to only crooks (and this is a solution that other people use too)
So, yeah, if there was a Enchantment API, this wouldn't happen, but yeah; They'll need to workaround the issue by having a null check before touching the enchantment's type
