### ISSUE TITLE
will 1.18.2 version work with Fabric too?

### ISSUE THREAD

**Issue by MSandro** [EnnuiL/CrookedCrooks#6]
hello, I noticed the commits for 1.18.2.
But you plan to port it to Quilt.
Will there be a Fabric Version too?
I can not find any 1.18.2 Version on CurseForge yet.
I would appreciate it very much if it were available soon.

**Comment by EnnuiL** [comment]
Nope, in the next version, this mod will completely switch to Quilt, with the Fabric version being unmaintained; Other than the main reason for switching my mods to it (better community, better API, better tools, etc.), there's a special reason why Crooked Crooks will migrate to it:

One of Crooked Crooks' dependencies was my own fork of MCDict (used in order to make the crook's effective blocks and their drop multipliers editable by the user), which was broken by the 1.18.2 tag refactor; Updating it would have been pretty difficult to do, but thankfully, the Quilt Standard Libraries had a new API, the Quilt Registry Entry Attributes API, which basically does the same thing as MCDict but better, and it has allowed me to easily update to 1.18.2 without worrying about the burden of maintaining MCDict and without having to remove a feature that would greatly help modpack creators with configuring the crooks;

The only thing left in order to release the Quilt 1.18.2 update is an external issue to be solved (which should be sorted out soonish), but yeah, basically, an update to 1.18.2 would have been extremely difficult and probably wouldn't have happened any time soon if not for Quilt

**Comment by MSandro** [comment]
Thanks, I understand. So I will add Crooks to my own Mod "Sky Fabricator", I hope its okay. I'm working on a 1.18.2 Sky modpack. But I don't assume that  Quilt is already ready for large modpacks in 1.18.2.
